### ISSUE TITLE
when will the code release?

### ISSUE THREAD

**Issue by lovejoker1102** [IGLICT/NEURALSLICE#1]

**Comment by jiang25262** [comment]
Thanks for your interest!

We've released demo code for fit deformable animal within single 4D tetrahedral mesh.

Apologies for the delayed code due to disk issues. Training code will follow soon.

**Comment by bluestyle97** [comment]
@jiang25262 Hi, this is a very interesting work. Could you please release the training code?

**Comment by jiang25262** [comment]
> @jiang25262 Hi, this is a very interesting work. Could you please release the training code?

Sorry for the late reply. 

I just submitted our training code. Feel free to contact me if you have any other questions!

**Comment by jiang25262** [comment]
> @jiang25262 Hi, this is a very interesting work. Could you please release the training code?

Sorry for the late reply. 

I just submitted our training code. Feel free to contact me if you have any other questions!
